language: go

go:
    - 1.8.x
    - tip
os:
  - linux
  - windows

notificaitons:
  email:
    recipients: your.email@host.com
    on_success: change
    on_failure: always

gobuild_args: -ldflags "-X main.Version=${TRAVIS_TAG} -X main.buildTime=`date -u '+%Y-%m-%d_%I:%M:%S%p'` -X main.commitId=${TRAVIS_COMMIT}"

env:
  - GOOS=linux GOARCH=amd64
  - GOOS=windows GOARCH=amd64
