sudo: false
language: go

go:
    - 1.8.x
    - tip
os:
  - linux
  - windows

notificaitons:
  email:
    recipients: avhimov@gmail.com
    on_success: change
    on_failure: always

env:
  - GOOS=linux GOARCH=amd64
  - GOOS=windows GOARCH=amd64

script:
 - go test -v ./...