language: go

go:
  - tip

install:
  - github.com/avhimkov/LogFileSize
script:
  # Testing scripts etc
  - "./build.sh"

#branches:
#  only:
#    - maste
#env:
#  # "gvm update" resets GOOS and GOARCH environment variable, workaround it by setting
#  # BUILD_GOOS and BUILD_GOARCH and overriding GOARCH and GOOS in the build script
#  global:
#    - BUILD_GOARCH=amd64
#  matrix:
#    - BUILD_GOOS=linux
#    - BUILD_GOOS=windows
#script:
#  - gvm cross $BUILD_GOOS $BUILD_GOARCH
#  - GOARCH=$BUILD_GOARCH GOOS=$BUILD_GOOS go build
#
#  # only test on linux
#  - if [ $BUILD_GOOS == "linux" ]; then GOARCH=$BUILD_GOARCH GOOS=$BUILD_GOOS go test -bench=.; fi

deploy:
  provider: releases
  skip_cleanup: true # Important, otherwise the build output would be purged.
  api_key:
    secure: lFGBaF...SJ1lDPDICY=
  file: bin/myawesomeapp
  on:
    repo: account/myawesomeproject
    tags: true # The deployment happens only if the commit has a tag.